spring:
  application:
    name: klaszo
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true&prepareThreshold=0

    username: postgres.whhuilavydzaibdzuler
    password: Supabase@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jwt.secret: mynameisshubhamsinghandiaambuildinganewprojectforeducationcenter
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
razorpay:
  key-id: ${RAZORPAY_KEY_ID}
  key-secret: ${RAZORPAY_KEY_SECRET}

cloudflare:
  r2:
    account-id: ${CLOUDFLARE_ACCOUNT_ID}
    access-key: ${CLOUDFLARE_ACCESS_KEY}
    secret-key: ${CLOUDFLARE_SECRET_KEY}
    bucket-name: ${CLOUDFLARE_BUCKET_NAME}
    public-url: ${CLOUDFLARE_PUBLIC_URL}
    
firebase:
  project-id: ${FIREBASE_PROJECT_ID}
  client-email: ${FIREBASE_CLIENT_EMAIL}
  private-key: ${FIREBASE_PRIVATE_KEY}
  private-key-id: ${FIREBASE_PRIVATE_KEY_ID}
  client-id: ${FIREBASE_CLIENT_ID}