spring:
  application:
    name: klaszo
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true
    username: postgres.whhuilavydzaibdzuler
    password: Supabase@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  jwt.secret: mynameisshubhamsinghandiaambuildinganewprojectforeducationcenter
razorpay:
  key-id: YOUR_RAZORPAY_KEY_ID
  key-secret: YOUR_RAZORPAY_KEY_SECRET